require "user.plugins"
require "user.options"
require "user.keymaps"
vim.cmd [[colorscheme gruvbox]]
require "user.completion"
require "user.lsp"
require "user.telescope"
require "user.autopairs"
require "user.treesitter"
require "user.toggleterm"
require "user.neotree"
